### ISSUE TITLE
Text input enabled causes segfault

### ISSUE THREAD

**Issue by parkerlreed** [migueletto/PumpkinOS#1]
Steam OS 3
gcc 12.2.0-1
sdl2 2.24.1-1

```
pumpkin = pit.loadlib("libos")
pumpkin.init()
pumpkin.start(1280, 720, 16, false, true, false, "Launcher")
```

gdb log 
[gdb.txt](https://github.com/migueletto/PumpkinOS/files/10748707/gdb.txt)

**Comment by migueletto** [comment]
I see you enabled the "dia" flag (5th argument to pumpkin.start). It is used make PumpkinOS looks like a PalmOS device: a 320x320 display plus a 320x160 input area. I have not paid much attention to this mode since I made big changes to the display code. Maybe something is broken there. Can you test with the flag to false and  report back?

**Comment by parkerlreed** [comment]
That being set to true is what's causing it. Runs fine normally with everything set to false. 

By "Text Input" I meant trying to enable the graffiti area (dia). Sorry for the bad wording.

![image](https://user-images.githubusercontent.com/841440/219230931-c11193ea-5f53-420e-abde-232a0a085473.png)

**Comment by migueletto** [comment]
Nice. There are indeed some missing files required to make DIA work. I will add them and test it to see if something still breaks. Thanks for the report.

**Comment by migueletto** [comment]
The latest commit should fix d the crash when using DIA. Please give it a try.

**Comment by parkerlreed** [comment]
Indeed it does! 
![image](https://user-images.githubusercontent.com/841440/219755482-6168ae86-036d-4a9f-a0ca-dc4ebe36df2f.png)

**Comment by parkerlreed** [comment]
Browsing around in DIA for a bit I eventually trigger a crash pressing Home

```
C:\home\deck\build\PumpkinOS>bash pumpkin.sh 
pumpkin.sh: line 3: 16869 Floating point exception(core dumped) ./pumpkin -d 1 -f pumpkin.log -s libscriptlua.so ./script/pumpkin_linux.lua
```

gdb log for this one 
[gdb.txt](https://github.com/migueletto/PumpkinOS/files/10770080/gdb.txt)

**Comment by migueletto** [comment]
I confirmed the bug here. I have just pushed a commit that should address this. But DIA mode is still pretty much untested. Other problems may arise. Appreciate your time to test things out.
