### ISSUE TITLE
Trouble installing resource PRC's

### ISSUE THREAD

**Issue by therion23** [migueletto/PumpkinOS#10]
Heya,

I tried installing the game Akheron, which consists of one PRC of type "appl" and three PRC's of the type "res ". However, PumpkinOS rejects the resource files with "Error deploying".

You can get the game from PalmDB (first one in the Games - RPG section) and see if you can recreate the error.

Oh, using the latest version pulled from git two days ago and compiled as you documented.

Regards,
Bo

**Comment by migueletto** [comment]
The problem was a null byte at the end of the resource type, which PumpkinOS was not expecting. I have fixed it to see if the game could start successfully, but it gave me a fatal exception. It seems Ackeron uses low level accesses to HW registers and that is making it crash under PumpkinOS.

**Comment by therion23** [comment]
Oh, okay. It was just strange that the first game i picked on PalmDB went like that - all the single file ones i have tried on PumpkinOS work just fine.

Anyway, no biggie, you might want to look into it in the future, so put it on your to-do list and close this issue please. I am sure there are other good RPGs to be played :)

Thank you for your time, keep up the good work!
