### ISSUE TITLE
Applications Jot and Plucker are crashing

### ISSUE THREAD

**Issue by og1en** [migueletto/PumpkinOS#15]
**jot**
 https://palmdb.net/app/jot crashing tutorial
**plucker** 1.8
 https://sourceforge.net/projects/plucker/ pl  FatalExeption: trap SysBatteryInfoV20 not mapped

**Comment by migueletto** [comment]
I have added the SysBatteryInfoV20 system call, but there are other issues preventing Plucker from working correctly.
Regarding Jot, it is crashing inside the emulated 68K code, but I am not sure what is the reason yet.

**Comment by migueletto** [comment]
After latest commits neither Jot or plucker are crashing anymore. Although there may be some minor problems with the UI, I am closing the original issue that was addressing the crash.

**Comment by migueletto** [comment]
Closing.
