### ISSUE TITLE
Captain's MiniGolf has input and graphics issues.

### ISSUE THREAD

**Issue by Hacker1245** [migueletto/PumpkinOS#19]
The game doesn't show the power and direction indicators properly, plus there doesn't seem to be a way to actually control the ball properly by dragging it.
Source code and game for reference: https://github.com/captaintouch/Captains_MiniGolf_PalmOS

**Comment by migueletto** [comment]
Looking into it.

**Comment by migueletto** [comment]
The latest commits should fix this problem. If you haven't synced PumpkinOS in a while, it is necessary
to clean and recompile from scratch, because of recent internal changes.

**Comment by Hacker1245** [comment]
Yeah, seems to work fine now.
