### ISSUE TITLE
Missing winsock2.h when compiling on Linux

### ISSUE THREAD

**Issue by agent725** [migueletto/PumpkinOS#9]
When attempting to compile PumpkinOS on Linux, I get the following error:
```
sys.c:7:10: fatal error: winsock2.h: No such file or directory
    7 | #include <winsock2.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: sys.o] Error 1
```

**Comment by migueletto** [comment]
winsock2.h is used only when compiling for Windows. For Linux, you should use "GNU/Linux" as the OS parameter for mk.sh.

**Comment by agent725** [comment]
Makes sense. Compiling now worked, thanks!

**Comment by migueletto** [comment]
Closed
